Repository jenkinsci/pom, pull requests merged in 2019-10, with the labels that each got.

#45 Add Dependabot configuration file
  .dependabot/config.yml
Labels: hacktoberfest, internal

#44 Update test-annotations from 1.2 to 1.3
  pom.xml
Labels: dependencies, hacktoberfest

#47 Add README
  README.md
Labels: documentation, hacktoberfest

#46 Update component name and description in the pom.xml to clarify the components purpose
  pom.xml
Labels: documentation, hacktoberfest
