Repository jenkinsci/pom, pull requests merged in 2021-11, with the labels that each got.

#188 Remove deprecated findbugs properties, directly use spotbugs properties
  pom.xml
Labels: chore

#196 Use enforcer 3.0.0 and matching extra enforcer rules
  pom.xml
Labels: dependencies

#198 Require Maven 3.8.1
  pom.xml
Labels: enhancement

#200 Exclude `servlet-api` from `requireUpperBoundDeps`
  pom.xml
Labels: bugfix, regression

#202 Ignore `jsr305` warnings
  pom.xml
Labels: bugfix
