Repository jenkinsci/pom, pull requests merged in 2022-07, with the labels that each got.

#273 [JENKINS-68919] Redirect test output to file when running all tests
  pom.xml
Labels: enhancement

#280 Skip yarn lint in `-P quick-build`
  pom.xml
Labels: enhancement

#285 build: Update extra-enforcer-rules to 1.6.1
  pom.xml
Labels: dependencies

#284 Upgrade Maven AntRun plugin
  pom.xml
Labels: dependencies, removed
