Repository jenkinsci/pom, pull requests merged in 2022-08, with the labels that each got.

#296 [JENKINS-69198] add jenkins-release profile to attach javadoc and sources jars
  pom.xml
Labels: bugfix

#300 Use JUnit BOM
  pom.xml
Labels: internal

#302 chore: Remove dead links
  pom.xml
Labels: chore

#303 Add correct archive URLs
  pom.xml
Labels: chore
