Repository jenkinsci/pom, pull requests merged in 2023-01, with the labels that each got.

#361 Remove japanese mailing list from pom
  pom.xml
Labels: chore

#362 Remove `forceJavacCompilerUse` workaround
  pom.xml
Labels: internal

#373 Consolidate `maven-surefire-plugin.version` and `maven-surefire-report-plugin.version`
  pom.xml
Labels: internal

#374 Use a name for the Stapler plugin property that is consistent with `plugin-pom`
  pom.xml
Labels: internal

#375 Remove obsolete Maven plugins
  pom.xml
Labels: removed

#372 Inline Maven property `incrementals.url` for Maven 4 support
  pom.xml
Labels: enhancement

#376 Sort version properties
  pom.xml
Labels: skip-changelog

#377 Remove unnecessary default group ID
  pom.xml
Labels: skip-changelog

#378 Remove unnecessary customization of remote repository update frequency
  pom.xml
Labels: removed

#379 Remove `defaultGoal`
  pom.xml
Labels: removed

#381 Eliminate some pointless inconsistency
  pom.xml
Labels: skip-changelog

#382 Remove unused property
  pom.xml
Labels: skip-changelog

#380 Define `releaseProfiles` in `<plugins>` section rather than `<pluginManagement>` section
  pom.xml
Labels: internal

#383 Fix `requireJavaVersion` range
  pom.xml
Labels: bug

#385 Ban `javax.servlet:servlet-api` version 0
  pom.xml
Labels: internal

#384 Remove unnecessary `enforceBytecodeVersion` excludes
  pom.xml
Labels: removed
